# -*- coding: utf-8 -*-
"""FootballMetrics_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgGhd-WSBt40d6AGi6fdonX-Hbak1VTz

# Kaggle
"""

import numpy as np
import os

import pandas as pd
import numpy as np
from zipfile import ZipFile
import zipfile
import os
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import seaborn as sns

!mkdir /root/.kaggle
!touch /root/.kaggle/kaggle.json
!echo '{"username":"ivanchuhonin","key":""}' > /root/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

# Просмотреть список файлов в датасете (опционально, для проверки)
!kaggle datasets files hubertsidorowicz/football-players-stats-2024-2025

# Скачать конкретный файл
!kaggle datasets download hubertsidorowicz/football-players-stats-2024-2025 -f players_data-2024_2025.csv

df = pd.read_csv('/content/players_data-2024_2025.csv')
df_sample1 = df.sample(1) # .reset_index(drop=True)

print(df_sample1.columns)

# Получаем список всех колонок с символом %
percent_columns = [col for col in df.columns if '%' in col]

print(f"Колонок с %: {len(percent_columns)}")
print("Список:")
for col in percent_columns:
    print(f"  - {col}")

df_sample1

# Найти вратарей с самым агрессивным стилем
aggressive_keepers = df[(df['Pos'] == 'GK') & (df['MP'] > 5)].nlargest(10, 'AvgDist')[['Player', 'Squad', 'MP', 'Age', 'AvgDist', '#OPA/90', 'Stp%']]

# Найти вратарей с лучшей игрой от ворот
build_up_keepers = df[(df['Pos'] == 'GK') & (df['MP'] > 5)].nsmallest(20, 'Launch%')[['Player', 'Squad', 'MP', 'Age', 'Launch%', 'Att (GK)', 'Thr']]

df[(df['MP'] > 8) & (df['Touches'] > 90)].nlargest(20, 'CPA')[['Player', 'Pos', 'Squad', 'MP', 'Age', 'Touches', 'PrgDist_stats_possession', 'CPA', '1/3_stats_possession']]
# (df['Squad'] == 'Real Madrid')

df[(df['MP'] > 10)].nlargest(10, 'TO')[['Player', 'Pos', 'Squad', 'MP', 'Age', 'Rec', 'Touches', 'TO', 'PrgDist_stats_possession', 'CPA', '1/3_stats_possession']]
# (df['Squad'] == 'Real Madrid')

# Найти лучших создателей моментов (минимум 15 матчей)
best_creators = df[
    (df['MP'] > 15) &
    (df['Min'] > 1000)
].nlargest(10, 'GCA90')[['Player', 'Squad', 'Pos', 'GCA', 'GCA90', 'SCA90']]

# Найти игроков с лучшими сквозными передачами
through_ball_maestros = df.nlargest(20, 'TB')[['Player', 'Squad', 'TB', 'GCA']]

# Найти лучших обороняющихся в атаке (прессинг)
high_press_players = df.nlargest(20, 'Att_stats_defense')[['Player', 'Squad', 'Att_stats_defense', 'TklW', 'Int']]
# 34 26
# Найти надежных защитников (много выносов, мало ошибок)
reliable_defenders = df[
    (df['Pos'].str.contains('DF')) &
    (df['MP'] > 15) & (df['Clr'] > 60)
].nlargest(10, 'Tkl%')[['Player', 'Squad', 'Clr', 'Err', 'Tkl%']]

reliable_defenders

# Найти лучших дриблеров (минимум 20 попыток)
best_dribblers = df[
    (df['Att_stats_possession'] > 50) &
    (df['MP'] > 10)
].nlargest(10, 'Succ%')[['Player', 'Squad', 'Pos', 'Att_stats_possession', 'Succ', 'Succ%']]

# Найти игроков, которые чаще всего продвигают мяч с дриблингом
progressive_carriers = df.nlargest(10, 'PrgC_stats_possession')[['Player', 'Squad', 'PrgC_stats_possession', 'CPA']]

# Найти игроков с лучшим контролем мяча (минимум потерь)
ball_controllers = df[
    (df['Touches'] > 500) &
    (df['MP'] > 15) & (df['Pos'] != 'GK') & (df['Rec'] > 1000)
].nsmallest(10, 'Mis')[['Player', 'MP', 'Squad', 'Touches', 'Mis', 'Dis', 'Rec']]

ball_controllers



best_keepers = df[(df['Pos'] == 'GK') & (df['MP'] > 10)].nlargest(10, 'PSxG+/-')
print("Лучшие вратари по предотвращенным голам:")
print(best_keepers[['Player', 'Squad', 'PSxG', 'GA_stats_keeper_adv', 'PSxG+/-']])

best_keepers = df_la_liga[(df_la_liga['Pos'] == 'GK') & (df_la_liga['MP'] > 10)].nlargest(10, 'PSxG+/-')
print("Лучшие вратари по предотвращенным голам:")
print(best_keepers[['Player', 'Squad', 'Age', 'PSxG', 'GA_stats_keeper_adv', 'PSxG+/-']])

df_la_liga = df[df['Comp']=="es La Liga"]

df_la_liga

# Display the dictionary keys to confirm variable names created
list(df_la_liga.keys())

team_chosen='Real Madrid'

# Define new metrics and their columns for comparison
metrics_columns = {
    "Gls": "Забитые голы",
    "Ast": "Голевые передачи",
    "G+A": "Голы + передачи",
    "CrdY": "Жёлтые карточки",
    "xG": "Ожидаемые голы",
    "xAG": "Ожидаемые голевые передачи",
    "PrgC": "Прогрессивные передачи",
    "PrgR": "Прогрессивные дриблинги",
    "xG+xAG": "Общий ожидаемый вклад",
    "Rk_stats_shooting": "Рейтинг в категории удары",
    "Gls_stats_shooting": "Место по голам в рейтинге ударов",
    "G+A-PK": "Голы+пасы без пенальти"
}

# Initialize dictionary to store all teams data for each metric
all_teams_data = {}

metrics_columns.items()

# Создаем подграфики: 4 строки, 3 колонки (для 12 метрик)
fig = make_subplots(
    rows=4,
    cols=3,
    subplot_titles=list(metrics_columns.values()),
    vertical_spacing=0.12,
    horizontal_spacing=0.1
)

# Итерация по всем метрикам
for idx, (metric_col, metric_name) in enumerate(metrics_columns.items()):
    if metric_col not in df_la_liga.columns:
        print(f"Внимание: Колонка {metric_col} отсутствует в DataFrame")
        continue

    # Определяем позицию подграфика
    row = idx // 3 + 1
    col = idx % 3 + 1

    try:
        # Сортируем игроков по текущей метрике и берем топ-20
        top_players = df_la_liga.nlargest(20, metric_col)

        # Для лучшей читаемости создаем сокращенные имена игроков
        player_labels = top_players['Player'].apply(
            lambda x: x[:15] + '...' if len(x) > 15 else x
        )

        # Создаем бар-график
        fig.add_trace(
            go.Bar(
                x=player_labels,
                y=top_players[metric_col],
                name=metric_name,
                text=top_players[metric_col],  # Показываем значения на графике
                textposition='auto',
                marker_color=px.colors.qualitative.Set2,
                hovertemplate='<b>%{x}</b><br>' +
                             f'{metric_name}: ' + '%{y:.1f}<br>' +
                             'Команда: ' + top_players['Squad'] +
                             '<extra></extra>'
            ),
            row=row, col=col
        )

        # Настройка осей для каждого подграфика
        fig.update_xaxes(
            tickangle=45,
            tickfont=dict(size=9),
            row=row, col=col
        )

        fig.update_yaxes(
            title_text=metric_name if col == 1 else '',
            title_font=dict(size=10),
            row=row, col=col
        )

    except Exception as e:
        print(f"Ошибка при обработке метрики {metric_col}: {e}")

# Настройка общего вида графика
fig.update_layout(
    title={
        'text': "Топ-20 игроков Ла Лиги по ключевым метрикам",
        'y': 0.98,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': dict(size=20)
    },
    showlegend=False,
    height=1200,  # Высота графика
    width=1400,   # Ширина графика
    margin=dict(t=100, b=50, l=50, r=50),
)

fig.show()

"""# EDA"""

# Просмотреть список файлов в датасете (опционально, для проверки)
!kaggle datasets files hubertsidorowicz/football-players-stats-2025-2026

# Скачать конкретный файл
!kaggle datasets download hubertsidorowicz/football-players-stats-2025-2026 -f players_data-2025_2026.csv

df = pd.read_csv('/content/players_data-2025_2026.csv')
df_sample1 = df.sample(1) # .reset_index(drop=True)

df_sample1

df

print(df.columns.tolist())

df[df['MP']==5].sample(40)

fm_df = df[df['MP']>4]

fm_df.to_csv('football_stats2026.csv')

team_chosen='Real Madrid'

# Define new metrics and their columns for comparison
metrics_columns = {
    "Gls": "голы",
    "Ast": "голевые передачи",
    "G+A": "Голы + передачи",
    "Sh": "всего ударов", ##
    "SoT": "удары в створ", ##
    "SoT%": "% ударов в створ", ##
    "Int": "перехваты", ##
    "Fls": "совершённые фолы", ##
    "Fld": "фолы на игроке (заработанные)", ##
    "Crs": "навесы", ##
    "TklW": "выигранные отборы", ##
    "CrdY": "жёлтые карточки"
}

# Initialize dictionary to store all teams data for each metric
all_teams_data = {}

metrics_columns.items()

# Создаем подграфики: 4 строки, 3 колонки (для 12 метрик)
fig = make_subplots(
    rows=4,
    cols=3,
    subplot_titles=list(metrics_columns.values()),
    vertical_spacing=0.12,
    horizontal_spacing=0.1
)

# Итерация по всем метрикам
for idx, (metric_col, metric_name) in enumerate(metrics_columns.items()):
    if metric_col not in df.columns:
        print(f"Внимание: Колонка {metric_col} отсутствует в DataFrame")
        continue

    # Определяем позицию подграфика
    row = idx // 3 + 1
    col = idx % 3 + 1

    try:
        # Сортируем игроков по текущей метрике и берем топ-20
        top_players = df.nlargest(20, metric_col)

        # Для лучшей читаемости создаем сокращенные имена игроков
        player_labels = top_players['Player'].apply(
            lambda x: x[:15] + '...' if len(x) > 15 else x
        )

        # Создаем бар-график
        fig.add_trace(
            go.Bar(
                x=player_labels,
                y=top_players[metric_col],
                name=metric_name,
                text=top_players[metric_col],  # Показываем значения на графике
                textposition='auto',
                marker_color=px.colors.qualitative.Set2,
                hovertemplate='<b>%{x}</b><br>' +
                             f'{metric_name}: ' + '%{y:.1f}<br>' +
                             'Команда: ' + top_players['Squad'] +
                             '<extra></extra>'
            ),
            row=row, col=col
        )

        # Настройка осей для каждого подграфика
        fig.update_xaxes(
            tickangle=45,
            tickfont=dict(size=9),
            row=row, col=col
        )

        fig.update_yaxes(
            title_text=metric_name if col == 1 else '',
            title_font=dict(size=10),
            row=row, col=col
        )

    except Exception as e:
        print(f"Ошибка при обработке метрики {metric_col}: {e}")

# Настройка общего вида графика
fig.update_layout(
    title={
        'text': "Топ-20 игроков по ключевым метрикам",
        'y': 0.98,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font': dict(size=20)
    },
    showlegend=False,
    height=1200,  # Высота графика
    width=1400,   # Ширина графика
    margin=dict(t=100, b=50, l=50, r=50),
)

fig.show()

"""# TG бот

загрузить файл с статистикой
"""

# !pip uninstall -y -q plotly kaleido
!pip install -q "plotly==5.24.1" "kaleido==0.2.1" "python-telegram-bot>=21.0" "rapidfuzz>=3.0" "pandas>=2.0"

import kaleido, plotly
print(kaleido.__version__, plotly.__version__)  # ожидаем 0.2.1  5.24.1

import plotly.graph_objects as go
go.Figure(go.Bar(x=[1,2], y=[3,4])).write_image("test.png")
print("kaleido работает ✅")

os.environ['TELEGRAM_BOT_TOKEN'] = '#ТОКЕН'

"""
Data processing layer for the football statistics bot.

The source CSV is a wide FBref-style export: it repeats block after block
(outfield / keeper / shooting / playing_time / misc), each block re-exporting
identity columns (Rk, Nation, Pos, Comp, Age, Born...) with a suffix like
``_stats_keeper``. This module collapses that into one tidy dataframe and
adds derived per-90 metrics and convenience lookup/query methods.

NOTE: this dataset does not contain xG / xA / dribbling stats. All "quality"
metrics below are built from what's actually available (goals, shots,
shots-on-target, assists, defensive actions, cards, etc).
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from functools import lru_cache
from typing import Optional

import numpy as np
import pandas as pd
from rapidfuzz import fuzz, process
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

logger = logging.getLogger(__name__)

# Columns kept from the base (outfield) block, renamed to clean names.
_BASE_COLUMNS = {
    "Player": "player",
    "Nation": "nation",
    "Pos": "pos",
    "Squad": "squad",
    "Comp": "comp",
    "Age": "age",
    "Born": "born",
    "MP": "mp",
    "Starts": "starts",
    "Min": "min",
    "90s": "nineties",
    "Gls": "gls",
    "Ast": "ast",
    "G+A": "g_plus_a",
    "G-PK": "g_minus_pk",
    "PK": "pk",
    "PKatt": "pk_att",
    "CrdY": "crdy",
    "CrdR": "crdr",
}

# Keeper block
_KEEPER_COLUMNS = {
    "GA": "gk_ga",
    "GA90": "gk_ga90",
    "SoTA": "gk_sota",
    "Saves": "gk_saves",
    "Save%": "gk_save_pct",
    "W": "gk_w",
    "D": "gk_d",
    "L": "gk_l",
    "CS": "gk_cs",
    "CS%": "gk_cs_pct",
    "PKA": "gk_pka",
    "PKsv": "gk_pksv",
    "PKm": "gk_pkm",
}

# Shooting block
_SHOOTING_COLUMNS = {
    "Sh": "sh",
    "SoT": "sot",
    "SoT%": "sot_pct",
    "Sh/90": "sh_90",
    "SoT/90": "sot_90",
    "G/Sh": "g_per_sh",
    "G/SoT": "g_per_sot",
}

# Playing time block
_PLAYING_TIME_COLUMNS = {
    "Mn/MP": "mn_per_mp",
    "Min%": "min_pct",
    "Mn/Start": "mn_per_start",
    "Compl": "compl",
    "Subs": "subs",
    "Mn/Sub": "mn_per_sub",
    "unSub": "un_sub",
    "PPM": "ppm",
    "onG": "on_g",
    "onGA": "on_ga",
    "+/-": "plus_minus",
    "+/-90": "plus_minus_90",
    "On-Off": "on_off",
}

# Misc block (defense / discipline)
_MISC_COLUMNS = {
    "2CrdY": "crdy2",
    "Fls": "fls",
    "Fld": "fld",
    "Off": "off",
    "Crs": "crs",
    "Int": "int_",
    "TklW": "tklw",
    "OG": "og",
}

# Human-readable descriptions, shown to the user in captions / menus.
STAT_DESCRIPTIONS: dict[str, str] = {
    "gls": "Голы",
    "ast": "Голевые передачи",
    "g_plus_a": "Голы + передачи",
    "gls_90": "Голы за 90 минут",
    "ast_90": "Передачи за 90 минут",
    "g_plus_a_90": "Голы + передачи за 90 минут",
    "sh": "Удары",
    "sot": "Удары в створ",
    "sot_pct": "Точность ударов, %",
    "g_per_sh": "Голы на удар (эффективность)",
    "crs": "Навесы",
    "int_": "Перехваты",
    "tklw": "Успешные отборы",
    "crdy": "Жёлтые карточки",
    "crdr": "Красные карточки",
    "gk_saves": "Сейвы (вратари)",
    "gk_save_pct": "% сейвов (вратари)",
    "gk_cs": "«Сухие» матчи (вратари)",
}

# Statistics offered in the bot menu (order matters — shown in this order).
MENU_STATS = [
    "gls",
    "ast",
    "g_plus_a",
    "gls_90",
    "ast_90",
    "g_plus_a_90",
    "sh",
    "sot_pct",
    "g_per_sh",
    "crs",
    "int_",
    "tklw",
    "crdy",
    "crdr",
]

POSITION_GROUPS: dict[str, str] = {
    "GK": "Вратари",
    "DF": "Защитники",
    "MF": "Полузащитники",
    "FW": "Нападающие",
}

# Feature sets used for similarity/clustering per position group. Kept in
# sync (same columns) with visualizer.RADAR_PRESETS so a "similar players"
# result and a radar comparison of the same two players tell a consistent
# story. GK is excluded from clustering — too few keepers per league for
# k-means to produce meaningful clusters.
CLUSTER_FEATURES: dict[str, list[str]] = {
    "FW": ["gls_90", "ast_90", "sot_pct", "g_per_sh", "sh_90"],
    "MF": ["gls_90", "ast_90", "crs_90", "int_90", "tklw_90"],
    "DF": ["tklw_90", "int_90", "crs_90", "ast_90", "crdy"],
}

# Scatter-plot metric pairs offered in the bot (x, y, x_label, y_label).
# No xG in this dataset, so "efficiency" is approximated from shooting stats.
SCATTER_PRESETS: dict[str, tuple[str, str, str, str]] = {
    "sot_pct": ("gls", "sot_pct", "Голы", "Точность ударов, %"),
    "g_per_sh": ("gls", "g_per_sh", "Голы", "Голы на удар (G/Sh)"),
}


@dataclass(frozen=True)
class PlayerMatch:
    player: str
    squad: str
    comp: str
    score: float


@dataclass(frozen=True)
class SimilarPlayer:
    player: str
    squad: str
    comp: str
    distance: float


class FootballDataProcessor:
    """Loads and serves the cleaned football statistics dataframe."""

    def __init__(self, csv_path: str, min_nineties_default: float = 3.0):
        self.csv_path = csv_path
        self.min_nineties_default = min_nineties_default
        self.df = self._load_and_clean(csv_path)

    # ------------------------------------------------------------------ #
    # Loading / cleaning
    # ------------------------------------------------------------------ #
    def _load_and_clean(self, csv_path: str) -> pd.DataFrame:
        raw = pd.read_csv(csv_path)

        frames = []
        rename_map = {**_BASE_COLUMNS}
        frames.append(raw[list(_BASE_COLUMNS.keys())].rename(columns=_BASE_COLUMNS))

        for block, suffix in (
            (_KEEPER_COLUMNS, ""),
            (_SHOOTING_COLUMNS, "_stats_shooting"),
            (_PLAYING_TIME_COLUMNS, "_stats_playing_time"),
            (_MISC_COLUMNS, "_stats_misc"),
        ):
            cols = {}
            for src, dst in block.items():
                candidate = src if src in raw.columns else f"{src}{suffix}"
                if candidate in raw.columns:
                    cols[candidate] = dst
                else:
                    logger.warning("Column %s not found in source CSV", src)
            frames.append(raw[list(cols.keys())].rename(columns=cols))

        df = pd.concat(frames, axis=1)

        # Normalize primary position (players can have "MF,FW" — take first).
        df["pos_primary"] = df["pos"].str.split(",").str[0].str.strip()

        # Clean competition names (drop the leading country code, e.g. "eng ").
        df["comp_clean"] = df["comp"].str.replace(
            r"^[a-z]{2,3}\s+", "", regex=True
        )

        # Numeric coercion for anything that should be numeric.
        numeric_cols = [c for c in df.columns if c not in (
            "player", "nation", "pos", "squad", "comp", "pos_primary", "comp_clean"
        )]
        for c in numeric_cols:
            df[c] = pd.to_numeric(df[c], errors="coerce")

        df = self._add_per90_metrics(df)
        df = df.dropna(subset=["player"]).reset_index(drop=True)
        logger.info("Loaded %d player rows from %s", len(df), csv_path)
        return df

    @staticmethod
    def _add_per90_metrics(df: pd.DataFrame) -> pd.DataFrame:
        safe_90s = df["nineties"].replace(0, pd.NA)
        df["gls_90"] = (df["gls"] / safe_90s).round(2)
        df["ast_90"] = (df["ast"] / safe_90s).round(2)
        df["g_plus_a_90"] = (df["g_plus_a"] / safe_90s).round(2)
        df["int_90"] = (df["int_"] / safe_90s).round(2)
        df["tklw_90"] = (df["tklw"] / safe_90s).round(2)
        df["crs_90"] = (df["crs"] / safe_90s).round(2)
        return df

    # ------------------------------------------------------------------ #
    # Menu helpers
    # ------------------------------------------------------------------ #
    def get_available_competitions(self) -> list[str]:
        return sorted(self.df["comp_clean"].dropna().unique().tolist())

    def get_competition_display_name(self, comp: str) -> str:
        return comp

    def get_available_statistics(self) -> list[str]:
        return MENU_STATS

    def get_stat_description(self, stat: str) -> str:
        return STAT_DESCRIPTIONS.get(stat, stat)

    def get_position_groups(self) -> dict[str, str]:
        return POSITION_GROUPS

    # ------------------------------------------------------------------ #
    # Queries
    # ------------------------------------------------------------------ #
    def get_top_players_by_stat(
        self,
        stat: str,
        competition: Optional[str] = None,
        position: Optional[str] = None,
        min_nineties: Optional[float] = None,
        top_n: int = 10,
    ) -> pd.DataFrame:
        """Top-N players by a given stat, optionally filtered by league/position.

        Cached via an internal hashable-args wrapper since DataFrames aren't
        hashable and can't be passed straight to lru_cache.
        """
        return self._cached_top_players(
            stat=stat,
            competition=competition,
            position=position,
            min_nineties=(
                self.min_nineties_default if min_nineties is None else min_nineties
            ),
            top_n=top_n,
        )

    @lru_cache(maxsize=256)
    def _cached_top_players(
        self,
        stat: str,
        competition: Optional[str],
        position: Optional[str],
        min_nineties: float,
        top_n: int,
    ) -> pd.DataFrame:
        if stat not in self.df.columns:
            return pd.DataFrame()

        sub = self.df[self.df["nineties"] >= min_nineties].copy()
        if competition:
            sub = sub[sub["comp_clean"] == competition]
        if position:
            sub = sub[sub["pos_primary"] == position]

        sub = sub.dropna(subset=[stat])
        sub = sub.sort_values(stat, ascending=False).head(top_n)
        return sub.reset_index(drop=True)

    def search_player(self, query: str, limit: int = 5) -> list[PlayerMatch]:
        """Fuzzy search by player name, returns candidate matches."""
        names = self.df["player"].dropna().unique().tolist()
        matches = process.extract(query, names, scorer=fuzz.WRatio, limit=limit)

        results = []
        seen = set()
        for name, score, _ in matches:
            rows = self.df[self.df["player"] == name]
            for _, row in rows.iterrows():
                key = (row["player"], row["squad"])
                if key in seen:
                    continue
                seen.add(key)
                results.append(
                    PlayerMatch(
                        player=row["player"],
                        squad=row["squad"],
                        comp=row["comp_clean"],
                        score=score,
                    )
                )
        return results[:limit]

    def get_player_row(self, player: str, squad: str) -> Optional[pd.Series]:
        rows = self.df[(self.df["player"] == player) & (self.df["squad"] == squad)]
        if rows.empty:
            return None
        return rows.iloc[0]

    # ------------------------------------------------------------------ #
    # Scatter data
    # ------------------------------------------------------------------ #
    def get_scatter_data(
        self,
        x_stat: str,
        y_stat: str,
        competition: Optional[str] = None,
        position: Optional[str] = None,
        min_nineties: Optional[float] = None,
        limit: int = 35,
    ) -> pd.DataFrame:
        """Players for a scatter plot, filtered and capped so the chart stays
        readable. Keeps the `limit` players with the most playing time
        (sturdier sample sizes -> less noisy percentages like SoT%)."""
        min_nineties = self.min_nineties_default if min_nineties is None else min_nineties
        sub = self.df[self.df["nineties"] >= min_nineties].copy()
        if competition:
            sub = sub[sub["comp_clean"] == competition]
        if position:
            sub = sub[sub["pos_primary"] == position]

        sub = sub.dropna(subset=[x_stat, y_stat])
        sub = sub.sort_values("nineties", ascending=False).head(limit)
        return sub.reset_index(drop=True)

    # ------------------------------------------------------------------ #
    # Clustering / similar players
    # ------------------------------------------------------------------ #
    @lru_cache(maxsize=16)
    def _compute_clusters(
        self, position_group: str, n_clusters: int, min_nineties: float
    ) -> pd.DataFrame:
        features = CLUSTER_FEATURES.get(position_group)
        if not features:
            return pd.DataFrame()

        sub = self.df[
            (self.df["pos_primary"] == position_group)
            & (self.df["nineties"] >= min_nineties)
        ].copy()
        sub = sub.dropna(subset=features)
        if len(sub) < n_clusters:
            sub["cluster"] = 0
            return sub.reset_index(drop=True)

        X = StandardScaler().fit_transform(sub[features])
        km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        sub["cluster"] = km.fit_predict(X)
        # Stash scaled features for distance lookups without recomputing.
        sub.attrs["scaled_features"] = X
        sub.attrs["feature_cols"] = features
        return sub.reset_index(drop=True)

    def find_similar_players(
        self,
        player: str,
        squad: str,
        n: int = 5,
        n_clusters: int = 5,
        min_nineties: Optional[float] = None,
    ) -> list[SimilarPlayer]:
        """Finds players in the same k-means cluster as `player`, ranked by
        Euclidean distance in standardized feature space (closest first)."""
        row = self.get_player_row(player, squad)
        if row is None:
            return []

        position_group = row["pos_primary"]
        if position_group not in CLUSTER_FEATURES:
            return []

        min_nineties = self.min_nineties_default if min_nineties is None else min_nineties
        clustered = self._compute_clusters(position_group, n_clusters, min_nineties)
        if clustered.empty:
            return []

        match_idx = clustered.index[
            (clustered["player"] == player) & (clustered["squad"] == squad)
        ]
        if len(match_idx) == 0:
            return []
        idx = match_idx[0]

        features = clustered.attrs["feature_cols"]
        X = clustered.attrs["scaled_features"]
        target_cluster = clustered.loc[idx, "cluster"]
        target_vec = X[idx]

        same_cluster = clustered[clustered["cluster"] == target_cluster]
        same_cluster = same_cluster[same_cluster.index != idx]

        distances = []
        for i in same_cluster.index:
            dist = float(np.linalg.norm(X[i] - target_vec))
            distances.append((i, dist))
        distances.sort(key=lambda t: t[1])

        results = []
        for i, dist in distances[:n]:
            r = clustered.loc[i]
            results.append(
                SimilarPlayer(
                    player=r["player"], squad=r["squad"], comp=r["comp_clean"], distance=dist
                )
            )
        return results

    # ------------------------------------------------------------------ #
    # Trends
    # ------------------------------------------------------------------ #
    def get_age_trend(
        self,
        stat: str,
        competition: Optional[str] = None,
        position: Optional[str] = None,
        min_nineties: Optional[float] = None,
        min_players_per_age: int = 3,
    ) -> pd.DataFrame:
        """Average `stat` by age (only ages with enough players to be
        meaningful, default >=3)."""
        min_nineties = self.min_nineties_default if min_nineties is None else min_nineties
        sub = self.df[self.df["nineties"] >= min_nineties].copy()
        if competition:
            sub = sub[sub["comp_clean"] == competition]
        if position:
            sub = sub[sub["pos_primary"] == position]

        sub = sub.dropna(subset=[stat, "age"])
        grouped = (
            sub.groupby("age")[stat]
            .agg(["mean", "count"])
            .reset_index()
            .rename(columns={"mean": "avg_value"})
        )
        grouped = grouped[grouped["count"] >= min_players_per_age]
        grouped["age"] = grouped["age"].astype(int)
        return grouped.sort_values("age").reset_index(drop=True)

    def get_league_trend(
        self,
        stat: str,
        position: Optional[str] = None,
        min_nineties: Optional[float] = None,
    ) -> pd.DataFrame:
        """Average `stat` per league (comp_clean)."""
        min_nineties = self.min_nineties_default if min_nineties is None else min_nineties
        sub = self.df[self.df["nineties"] >= min_nineties].copy()
        if position:
            sub = sub[sub["pos_primary"] == position]

        sub = sub.dropna(subset=[stat])
        grouped = (
            sub.groupby("comp_clean")[stat]
            .agg(["mean", "count"])
            .reset_index()
            .rename(columns={"mean": "avg_value", "comp_clean": "league"})
        )
        return grouped.sort_values("avg_value", ascending=False).reset_index(drop=True)

"""
Plotly-based chart generation for the football statistics bot.
Renders to static PNG (via kaleido) so charts can be sent as Telegram photos.
"""
from __future__ import annotations

from typing import Optional

import pandas as pd
import plotly.graph_objects as go

PRIMARY = "#3D5AFE"
ACCENT = "#FF6E40"
BG = "#0F1115"
GRID = "#2A2E37"
TEXT = "#E8E8E8"

# Radar chart metric presets per position group. Each tuple is
# (column_name, human label). Kept intentionally short (5-6 axes read best).
RADAR_PRESETS: dict[str, list[tuple[str, str]]] = {
    "FW": [
        ("gls_90", "Голы/90"),
        ("ast_90", "Передачи/90"),
        ("sot_pct", "Точность ударов %"),
        ("g_per_sh", "Гол/удар"),
        ("sh_90", "Удары/90"),
    ],
    "MF": [
        ("gls_90", "Голы/90"),
        ("ast_90", "Передачи/90"),
        ("crs_90", "Навесы/90"),
        ("int_90", "Перехваты/90"),
        ("tklw_90", "Отборы/90"),
    ],
    "DF": [
        ("tklw_90", "Отборы/90"),
        ("int_90", "Перехваты/90"),
        ("crs_90", "Навесы/90"),
        ("ast_90", "Передачи/90"),
        ("crdy", "Жёлтые карточки"),
    ],
    "GK": [
        ("gk_save_pct", "% сейвов"),
        ("gk_cs_pct", "% сухих матчей"),
        ("gk_ga90", "Пропущено/90"),
        ("gk_saves", "Сейвы (всего)"),
    ],
}


class FootballVisualizer:
    def _base_layout(self, title: str) -> dict:
        return dict(
            title=dict(text=title, font=dict(size=20, color=TEXT)),
            paper_bgcolor=BG,
            plot_bgcolor=BG,
            font=dict(color=TEXT, size=13),
            margin=dict(l=120, r=40, t=80, b=40),
        )

    # ------------------------------------------------------------------ #
    def create_top_players_chart(
        self,
        data: pd.DataFrame,
        stat: str,
        stat_label: str,
        competition: Optional[str],
        position: Optional[str],
        output_path: str,
    ) -> str:
        data = data.iloc[::-1]  # so #1 ends up on top of a horizontal bar
        labels = [f"{p} ({s})" for p, s in zip(data["player"], data["squad"])]

        fig = go.Figure(
            go.Bar(
                x=data[stat],
                y=labels,
                orientation="h",
                marker=dict(
                    color=data[stat],
                    colorscale=[[0, PRIMARY], [1, ACCENT]],
                ),
                text=data[stat].round(2),
                textposition="outside",
            )
        )

        subtitle_bits = [competition or "Все лиги"]
        if position:
            subtitle_bits.append(position)
        title = f"Топ-{len(data)} по «{stat_label}»<br><sup>{' · '.join(subtitle_bits)}</sup>"

        fig.update_layout(**self._base_layout(title))
        fig.update_xaxes(gridcolor=GRID, zerolinecolor=GRID)
        fig.update_yaxes(gridcolor=GRID)
        fig.update_layout(height=120 + 40 * len(data), width=900)

        fig.write_image(output_path, scale=2)
        return output_path

    # ------------------------------------------------------------------ #
    def create_radar_chart(
        self,
        player1: pd.Series,
        player2: pd.Series,
        position_group: str,
        output_path: str,
    ) -> str:
        metrics = RADAR_PRESETS.get(position_group, RADAR_PRESETS["MF"])
        cols = [c for c, _ in metrics]
        labels = [lbl for _, lbl in metrics]

        # Normalize each axis 0-1 against the max of the two players (avoids
        # one huge outlier axis squashing everything else).
        vals1, vals2 = [], []
        for c in cols:
            v1 = float(player1.get(c) or 0)
            v2 = float(player2.get(c) or 0)
            m = max(v1, v2, 1e-6)
            vals1.append(v1 / m)
            vals2.append(v2 / m)

        fig = go.Figure()
        fig.add_trace(
            go.Scatterpolar(
                r=vals1 + vals1[:1],
                theta=labels + labels[:1],
                fill="toself",
                name=f"{player1['player']} ({player1['squad']})",
                line=dict(color=PRIMARY),
            )
        )
        fig.add_trace(
            go.Scatterpolar(
                r=vals2 + vals2[:1],
                theta=labels + labels[:1],
                fill="toself",
                name=f"{player2['player']} ({player2['squad']})",
                line=dict(color=ACCENT),
            )
        )

        fig.write_image(output_path, scale=2)
        return output_path

    # ------------------------------------------------------------------ #
    def create_scatter_chart(
        self,
        data: pd.DataFrame,
        x_stat: str,
        y_stat: str,
        x_label: str,
        y_label: str,
        competition: Optional[str],
        position: Optional[str],
        output_path: str,
    ) -> str:
        labels = [f"{p} ({s})" for p, s in zip(data["player"], data["squad"])]

        fig = go.Figure(
            go.Scatter(
                x=data[x_stat],
                y=data[y_stat],
                mode="markers+text",
                text=data["player"],
                textposition="top center",
                textfont=dict(size=9, color=TEXT),
                marker=dict(
                    size=12,
                    color=data[x_stat],
                    colorscale=[[0, PRIMARY], [1, ACCENT]],
                    line=dict(width=1, color=BG),
                ),
                hovertext=labels,
                hoverinfo="text",
            )
        )

        # Mean reference lines help spot over/under performers at a glance.
        fig.add_hline(y=data[y_stat].mean(), line_dash="dot", line_color=GRID)
        fig.add_vline(x=data[x_stat].mean(), line_dash="dot", line_color=GRID)

        subtitle_bits = [competition or "Все лиги"]
        if position:
            subtitle_bits.append(position)
        title = f"{x_label} vs {y_label}<br><sup>{' · '.join(subtitle_bits)}</sup>"

        fig.update_layout(**self._base_layout(title))
        fig.update_xaxes(title=x_label, gridcolor=GRID, zerolinecolor=GRID)
        fig.update_yaxes(title=y_label, gridcolor=GRID, zerolinecolor=GRID)
        fig.update_layout(width=900, height=650, showlegend=False)

        fig.write_image(output_path, scale=2)
        return output_path

    # ------------------------------------------------------------------ #
    def create_age_trend_chart(
        self, data: pd.DataFrame, stat_label: str, subtitle: str, output_path: str
    ) -> str:
        fig = go.Figure(
            go.Scatter(
                x=data["age"],
                y=data["avg_value"],
                mode="lines+markers",
                line=dict(color=PRIMARY, width=3),
                marker=dict(size=8, color=ACCENT),
                hovertext=[f"n={c} игроков" for c in data["count"]],
                hoverinfo="x+y+text",
            )
        )
        fig.update_layout(
            **self._base_layout(f"«{stat_label}» по возрасту<br><sup>{subtitle}</sup>")
        )
        fig.update_xaxes(title="Возраст", gridcolor=GRID, dtick=1)
        fig.update_yaxes(title=stat_label, gridcolor=GRID)
        fig.update_layout(width=900, height=550)

        fig.write_image(output_path, scale=2)
        return output_path

    # ------------------------------------------------------------------ #
    def create_league_trend_chart(
        self, data: pd.DataFrame, stat_label: str, subtitle: str, output_path: str
    ) -> str:
        data = data.sort_values("avg_value")
        fig = go.Figure(
            go.Bar(
                x=data["avg_value"],
                y=data["league"],
                orientation="h",
                marker=dict(
                    color=data["avg_value"],
                    colorscale=[[0, PRIMARY], [1, ACCENT]],
                ),
                text=data["avg_value"].round(2),
                textposition="outside",
                hovertext=[f"n={c} игроков" for c in data["count"]],
            )
        )
        fig.update_layout(
            **self._base_layout(f"«{stat_label}» по лигам<br><sup>{subtitle}</sup>")
        )
        fig.update_xaxes(title=stat_label, gridcolor=GRID)
        fig.update_yaxes(gridcolor=GRID)
        fig.update_layout(width=900, height=400)

        fig.write_image(output_path, scale=2)
        return output_path

"""
Telegram bot for football statistics analysis.

UX is built entirely on inline keyboards (CallbackQueryHandler) instead of
ReplyKeyboardMarkup: menus are edited in place rather than re-sent, and long
lists (statistics) are paginated with Prev/Next buttons.

Five flows, all reachable from the main menu:
  - "Топ игроков"          : competition -> position -> stat -> bar chart
  - "Сравнить игроков"      : search player 1 -> pick -> search player 2 ->
                               pick -> radar chart
  - "Голы vs эффективность" : competition -> position -> metric pair ->
                               scatter chart
  - "Похожие игроки"        : search player -> pick -> k-means neighbours
                               (+ radar chart vs the closest match)
  - "Тренды"                : age or league -> stat -> line/bar chart
"""
from __future__ import annotations

import asyncio
import logging
import os
import sys
from typing import Optional

IN_COLAB = False
try:
    if "google.colab" in sys.modules or "IPython" in sys.modules:
        import nest_asyncio
        nest_asyncio.apply()
        IN_COLAB = True
except ImportError:
    pass
except Exception as e:
    print(f"Warning: Could not apply nest_asyncio: {e}")

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import (
    Application,
    CallbackQueryHandler,
    CommandHandler,
    ConversationHandler,
    ContextTypes,
    MessageHandler,
    filters,
)


logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------- #
# Conversation states
# ---------------------------------------------------------------------- #
(
    MAIN_MENU,
    CHOOSE_COMPETITION,
    CHOOSE_POSITION,
    CHOOSE_STAT,
    CMP_SEARCH_1,
    CMP_PICK_1,
    CMP_SEARCH_2,
    CMP_PICK_2,
    SCATTER_COMPETITION,
    SCATTER_POSITION,
    SCATTER_METRIC,
    SIMILAR_SEARCH,
    SIMILAR_PICK,
    TREND_TYPE,
    TREND_STAT,
) = range(15)

STATS_PER_PAGE = 6

CSV_PATH = os.getenv("FOOTBALL_CSV_PATH", "football_stats.csv")

try:
    data_processor = FootballDataProcessor(CSV_PATH)
    visualizer = FootballVisualizer()
except Exception as e:
    logger.error("Could not initialize data processor: %s", e)
    data_processor = None
    visualizer = None


# ---------------------------------------------------------------------- #
# Small keyboard-building helpers
# ---------------------------------------------------------------------- #
def _chunk(buttons: list[InlineKeyboardButton], per_row: int = 2) -> list:
    return [buttons[i : i + per_row] for i in range(0, len(buttons), per_row)]


def main_menu_keyboard() -> InlineKeyboardMarkup:
    kb = [
        [InlineKeyboardButton("📊 Топ игроков", callback_data="menu:top")],
        [InlineKeyboardButton("⚔️ Сравнить игроков", callback_data="menu:compare")],
        [InlineKeyboardButton("🎯 Голы vs эффективность", callback_data="menu:scatter")],
        [InlineKeyboardButton("🧬 Похожие игроки", callback_data="menu:similar")],
        [InlineKeyboardButton("📈 Тренды", callback_data="menu:trend")],
    ]
    return InlineKeyboardMarkup(kb)


def competition_keyboard() -> InlineKeyboardMarkup:
    comps = data_processor.get_available_competitions()
    buttons = [InlineKeyboardButton(c, callback_data=f"comp:{c}") for c in comps]
    kb = _chunk(buttons, 2)
    kb.append([InlineKeyboardButton("🌍 Все лиги", callback_data="comp:all")])
    kb.append([InlineKeyboardButton("⬅️ Назад", callback_data="back:main")])
    return InlineKeyboardMarkup(kb)


def position_keyboard(back_target: str = "back:competition") -> InlineKeyboardMarkup:
    groups = data_processor.get_position_groups()
    buttons = [
        InlineKeyboardButton(label, callback_data=f"pos:{code}")
        for code, label in groups.items()
    ]
    kb = _chunk(buttons, 2)
    kb.append([InlineKeyboardButton("👥 Все позиции", callback_data="pos:all")])
    kb.append([InlineKeyboardButton("⬅️ Назад", callback_data=back_target)])
    return InlineKeyboardMarkup(kb)


def stat_keyboard(page: int = 0, back_target: str = "back:position") -> InlineKeyboardMarkup:
    stats = data_processor.get_available_statistics()
    start = page * STATS_PER_PAGE
    page_stats = stats[start : start + STATS_PER_PAGE]

    buttons = [
        InlineKeyboardButton(
            data_processor.get_stat_description(s), callback_data=f"stat:{s}"
        )
        for s in page_stats
    ]
    kb = _chunk(buttons, 2)

    nav_row = []
    if page > 0:
        nav_row.append(InlineKeyboardButton("◀️", callback_data=f"statpage:{page - 1}"))
    total_pages = (len(stats) - 1) // STATS_PER_PAGE + 1
    nav_row.append(
        InlineKeyboardButton(f"{page + 1}/{total_pages}", callback_data="noop")
    )
    if start + STATS_PER_PAGE < len(stats):
        nav_row.append(InlineKeyboardButton("▶️", callback_data=f"statpage:{page + 1}"))
    kb.append(nav_row)
    kb.append([InlineKeyboardButton("⬅️ Назад", callback_data=back_target)])
    return InlineKeyboardMarkup(kb)


def scatter_metric_keyboard() -> InlineKeyboardMarkup:
    buttons = []
    for key, (_, _, x_label, y_label) in SCATTER_PRESETS.items():
        buttons.append(
            InlineKeyboardButton(
                f"{x_label} vs {y_label}", callback_data=f"smetric:{key}"
            )
        )
    kb = [[b] for b in buttons]
    kb.append([InlineKeyboardButton("⬅️ Назад", callback_data="back:main")])
    return InlineKeyboardMarkup(kb)


def trend_type_keyboard() -> InlineKeyboardMarkup:
    kb = [
        [InlineKeyboardButton("📅 По возрасту", callback_data="trendtype:age")],
        [InlineKeyboardButton("🏆 По лигам", callback_data="trendtype:league")],
        [InlineKeyboardButton("⬅️ Назад", callback_data="back:main")],
    ]
    return InlineKeyboardMarkup(kb)


def search_results_keyboard(matches, prefix: str) -> InlineKeyboardMarkup:
    buttons = [
        InlineKeyboardButton(
            f"{m.player} ({m.squad}, {m.comp})", callback_data=f"{prefix}:{i}"
        )
        for i, m in enumerate(matches)
    ]
    kb = [[b] for b in buttons]
    kb.append([InlineKeyboardButton("❌ Отмена", callback_data="back:main")])
    return InlineKeyboardMarkup(kb)


def again_keyboard() -> InlineKeyboardMarkup:
    """Shown after a result (chart/error). 'Продолжить' takes the user back
    to the main menu, 'Закончить' ends the conversation cleanly."""
    kb = [
        [InlineKeyboardButton("▶️ Продолжить", callback_data="cont:menu")],
        [InlineKeyboardButton("🏁 Закончить", callback_data="cont:end")],
    ]
    return InlineKeyboardMarkup(kb)


# ---------------------------------------------------------------------- #
# Entry points
# ---------------------------------------------------------------------- #
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    context.user_data.clear()
    user = update.effective_user
    text = (
        f"Привет, {user.first_name}! 👋⚽\n\n"
        "Я показываю статистику игроков топ-5 лиг Европы.\n"
        "Что хотите сделать?"
    )
    if update.message:
        await update.message.reply_text(text, reply_markup=main_menu_keyboard())
    else:
        await update.callback_query.edit_message_text(
            text, reply_markup=main_menu_keyboard()
        )
    return MAIN_MENU


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "⚽ Football Statistics Bot\n\n"
        "/start — главное меню\n"
        "/cancel — отменить текущее действие\n\n"
        "«Топ игроков» — топ-10 по статистике с фильтром по лиге и позиции.\n"
        "«Сравнить игроков» — radar-диаграмма сравнения двух игроков.\n"
        "«Голы vs эффективность» — scatter-график, кто перебивает/недобивает "
        "по реализации моментов.\n"
        "«Похожие игроки» — поиск игроков со схожим стилем (кластеризация).\n"
        "«Тренды» — как статистика меняется по возрасту или отличается по лигам."
    )


async def cancel(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    context.user_data.clear()
    await update.message.reply_text("Отменено. /start — чтобы начать заново.")
    return ConversationHandler.END


# ---------------------------------------------------------------------- #
# Main menu routing
# ---------------------------------------------------------------------- #
async def on_main_menu(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()

    if query.data == "menu:top":
        await query.edit_message_text(
            "Выберите лигу:", reply_markup=competition_keyboard()
        )
        return CHOOSE_COMPETITION

    if query.data == "menu:compare":
        await query.edit_message_text(
            "Введите имя первого игрока (можно частично, например 'Salah'):"
        )
        return CMP_SEARCH_1

    if query.data == "menu:scatter":
        await query.edit_message_text(
            "Выберите лигу:", reply_markup=competition_keyboard()
        )
        return SCATTER_COMPETITION

    if query.data == "menu:similar":
        await query.edit_message_text(
            "Введите имя игрока, чтобы найти похожих на него "
            "(по стилю игры среди игроков той же позиции):"
        )
        return SIMILAR_SEARCH

    if query.data == "menu:trend":
        await query.edit_message_text(
            "Что показать?", reply_markup=trend_type_keyboard()
        )
        return TREND_TYPE

    return MAIN_MENU


async def on_continue(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    """Handles the 'Продолжить' / 'Закончить' buttons shown after a result."""
    query = update.callback_query
    await query.answer()
    action = query.data.split(":", 1)[1]

    if action == "end":
        context.user_data.clear()
        await query.edit_message_text(
            "Спасибо, что воспользовались ботом! ⚽\n/start — чтобы начать заново."
        )
        return ConversationHandler.END

    # action == "menu": back to the main menu
    context.user_data.clear()
    await query.edit_message_text(
        "Что хотите сделать дальше?", reply_markup=main_menu_keyboard()
    )
    return MAIN_MENU


async def on_back(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    target = query.data.split(":")[1]

    if target == "main":
        await query.edit_message_text(
            "Что хотите сделать?", reply_markup=main_menu_keyboard()
        )
        return MAIN_MENU
    if target == "competition":
        await query.edit_message_text(
            "Выберите лигу:", reply_markup=competition_keyboard()
        )
        return CHOOSE_COMPETITION
    if target == "position":
        await query.edit_message_text(
            "Выберите позицию:", reply_markup=position_keyboard()
        )
        return CHOOSE_POSITION

    return MAIN_MENU


# ---------------------------------------------------------------------- #
# "Топ игроков" flow
# ---------------------------------------------------------------------- #
async def on_competition(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    comp = query.data.split(":", 1)[1]
    context.user_data["competition"] = None if comp == "all" else comp

    await query.edit_message_text("Выберите позицию:", reply_markup=position_keyboard())
    return CHOOSE_POSITION


async def on_position(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    pos = query.data.split(":", 1)[1]
    context.user_data["position"] = None if pos == "all" else pos

    await query.edit_message_text(
        "Выберите статистику:", reply_markup=stat_keyboard(0)
    )
    return CHOOSE_STAT


async def on_stat_page(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    page = int(query.data.split(":")[1])
    await query.edit_message_reply_markup(reply_markup=stat_keyboard(page))
    return CHOOSE_STAT


async def on_stat(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    stat = query.data.split(":", 1)[1]

    competition = context.user_data.get("competition")
    position = context.user_data.get("position")

    await query.edit_message_text("📊 Считаю...")

    top_players = data_processor.get_top_players_by_stat(
        stat=stat, competition=competition, position=position, top_n=10
    )

    if top_players.empty:
        await query.edit_message_text(
            "Нет данных под эти фильтры. Попробуйте другую комбинацию.",
            reply_markup=again_keyboard(),
        )
        return MAIN_MENU

    output_path = f"temp_chart_{update.effective_user.id}.png"
    visualizer.create_top_players_chart(
        data=top_players,
        stat=stat,
        stat_label=data_processor.get_stat_description(stat),
        competition=competition,
        position=position,
        output_path=output_path,
    )

    caption_lines = [
        f"📈 Топ-{len(top_players)} по «{data_processor.get_stat_description(stat)}»",
        f"🏆 {competition or 'Все лиги'}" + (f" · {position}" if position else ""),
        "",
    ]
    for i, row in top_players.iterrows():
        val = row[stat]
        val_str = f"{val:.2f}" if isinstance(val, float) else str(val)
        caption_lines.append(f"{i + 1}. {row['player']} ({row['squad']}): {val_str}")

    with open(output_path, "rb") as photo:
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=photo,
            caption="\n".join(caption_lines),
        )
    if os.path.exists(output_path):
        os.remove(output_path)

    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Хотите ещё что-нибудь посмотреть?",
        reply_markup=again_keyboard(),
    )
    return MAIN_MENU


# ---------------------------------------------------------------------- #
# "Сравнить игроков" flow
# ---------------------------------------------------------------------- #
async def _handle_player_search(
    update: Update, context: ContextTypes.DEFAULT_TYPE, slot: int
) -> int:
    query_text = update.message.text.strip()
    matches = data_processor.search_player(query_text, limit=5)

    if not matches:
        await update.message.reply_text(
            "Никого не нашёл. Попробуйте ещё раз или /cancel."
        )
        return CMP_SEARCH_1 if slot == 1 else CMP_SEARCH_2

    context.user_data[f"candidates_{slot}"] = matches
    await update.message.reply_text(
        "Кого из них вы имели в виду?",
        reply_markup=search_results_keyboard(matches, prefix=f"p{slot}"),
    )
    return CMP_PICK_1 if slot == 1 else CMP_PICK_2


async def on_search_player1(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    return await _handle_player_search(update, context, slot=1)


async def on_search_player2(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    return await _handle_player_search(update, context, slot=2)


async def on_pick_player1(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    idx = int(query.data.split(":")[1])
    match = context.user_data["candidates_1"][idx]
    context.user_data["player1"] = (match.player, match.squad)

    await query.edit_message_text(
        f"Игрок 1: {match.player} ({match.squad}) ✅\n\n"
        "Теперь введите имя второго игрока:"
    )
    return CMP_SEARCH_2


async def on_pick_player2(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    idx = int(query.data.split(":")[1])
    match = context.user_data["candidates_2"][idx]
    context.user_data["player2"] = (match.player, match.squad)

    await query.edit_message_text("⚔️ Строю сравнение...")

    p1_name, p1_squad = context.user_data["player1"]
    p2_name, p2_squad = match.player, match.squad

    row1 = data_processor.get_player_row(p1_name, p1_squad)
    row2 = data_processor.get_player_row(p2_name, p2_squad)

    if row1 is None or row2 is None:
        await query.edit_message_text(
            "Не удалось найти данные одного из игроков.",
            reply_markup=again_keyboard(),
        )
        return MAIN_MENU

    position_group = row1["pos_primary"] if row1["pos_primary"] == row2["pos_primary"] else "MF"

    output_path = f"temp_radar_{update.effective_user.id}.png"
    visualizer.create_radar_chart(row1, row2, position_group, output_path)

    with open(output_path, "rb") as photo:
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=photo,
            caption=f"⚔️ {p1_name} ({p1_squad}) vs {p2_name} ({p2_squad})",
        )
    if os.path.exists(output_path):
        os.remove(output_path)

    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Хотите ещё что-нибудь посмотреть?",
        reply_markup=again_keyboard(),
    )
    return MAIN_MENU


async def noop(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.callback_query.answer()


# ---------------------------------------------------------------------- #
# "Голы vs эффективность" (scatter) flow
# ---------------------------------------------------------------------- #
async def on_scatter_competition(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    comp = query.data.split(":", 1)[1]
    context.user_data["scatter_competition"] = None if comp == "all" else comp

    await query.edit_message_text(
        "Выберите позицию:", reply_markup=position_keyboard(back_target="back:main")
    )
    return SCATTER_POSITION


async def on_scatter_position(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    pos = query.data.split(":", 1)[1]
    context.user_data["scatter_position"] = None if pos == "all" else pos

    await query.edit_message_text(
        "Какую пару метрик сравнить?", reply_markup=scatter_metric_keyboard()
    )
    return SCATTER_METRIC


async def on_scatter_metric(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    key = query.data.split(":", 1)[1]
    x_stat, y_stat, x_label, y_label = SCATTER_PRESETS[key]

    competition = context.user_data.get("scatter_competition")
    position = context.user_data.get("scatter_position")

    await query.edit_message_text("📊 Считаю...")

    data = data_processor.get_scatter_data(
        x_stat, y_stat, competition=competition, position=position, limit=30
    )
    if data.empty:
        await query.edit_message_text(
            "Нет данных под эти фильтры. Попробуйте другую комбинацию.",
            reply_markup=again_keyboard(),
        )
        return MAIN_MENU

    output_path = f"temp_scatter_{update.effective_user.id}.png"
    visualizer.create_scatter_chart(
        data, x_stat, y_stat, x_label, y_label, competition, position, output_path
    )

    with open(output_path, "rb") as photo:
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=photo,
            caption=(
                f"🎯 {x_label} vs {y_label}\n"
                f"🏆 {competition or 'Все лиги'}" + (f" · {position}" if position else "")
                + f"\n\nПунктир — среднее значение по выборке ({len(data)} игроков)."
            ),
        )
    if os.path.exists(output_path):
        os.remove(output_path)

    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Хотите ещё что-нибудь посмотреть?",
        reply_markup=again_keyboard(),
    )
    return MAIN_MENU


# ---------------------------------------------------------------------- #
# "Похожие игроки" flow
# ---------------------------------------------------------------------- #
async def on_search_similar(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query_text = update.message.text.strip()
    matches = data_processor.search_player(query_text, limit=5)

    if not matches:
        await update.message.reply_text(
            "Никого не нашёл. Попробуйте ещё раз или /cancel."
        )
        return SIMILAR_SEARCH

    context.user_data["candidates_similar"] = matches
    await update.message.reply_text(
        "Кого из них вы имели в виду?",
        reply_markup=search_results_keyboard(matches, prefix="sim"),
    )
    return SIMILAR_PICK


async def on_pick_similar(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    idx = int(query.data.split(":")[1])
    match = context.user_data["candidates_similar"][idx]

    await query.edit_message_text("🧬 Ищу похожих игроков...")

    similar = data_processor.find_similar_players(match.player, match.squad, n=5)

    if not similar:
        await query.edit_message_text(
            "Не нашлось похожих игроков — либо для вратарей (пока не поддерживается), "
            "либо слишком мало игроков той же позиции с достаточным игровым временем.",
            reply_markup=again_keyboard(),
        )
        return MAIN_MENU

    lines = [f"🧬 Похожие на {match.player} ({match.squad}) по стилю игры:", ""]
    for i, s in enumerate(similar, 1):
        lines.append(f"{i}. {s.player} ({s.squad}, {s.comp})")

    row1 = data_processor.get_player_row(match.player, match.squad)
    top = similar[0]
    row2 = data_processor.get_player_row(top.player, top.squad)

    output_path = f"temp_similar_{update.effective_user.id}.png"
    if row1 is not None and row2 is not None:
        visualizer.create_radar_chart(row1, row2, row1["pos_primary"], output_path)
        with open(output_path, "rb") as photo:
            await context.bot.send_photo(
                chat_id=update.effective_chat.id,
                photo=photo,
                caption="\n".join(lines),
            )
        if os.path.exists(output_path):
            os.remove(output_path)
    else:
        await context.bot.send_message(
            chat_id=update.effective_chat.id, text="\n".join(lines)
        )

    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Хотите ещё что-нибудь посмотреть?",
        reply_markup=again_keyboard(),
    )
    return MAIN_MENU


# ---------------------------------------------------------------------- #
# "Тренды" flow
# ---------------------------------------------------------------------- #
async def on_trend_type(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    trend_type = query.data.split(":", 1)[1]
    context.user_data["trend_type"] = trend_type

    await query.edit_message_text(
        "Выберите статистику:", reply_markup=stat_keyboard(0, back_target="back:main")
    )
    return TREND_STAT


async def on_trend_stat_page(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    page = int(query.data.split(":")[1])
    await query.edit_message_reply_markup(
        reply_markup=stat_keyboard(page, back_target="back:main")
    )
    return TREND_STAT


async def on_trend_stat(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    query = update.callback_query
    await query.answer()
    stat = query.data.split(":", 1)[1]
    trend_type = context.user_data.get("trend_type", "age")
    stat_label = data_processor.get_stat_description(stat)

    await query.edit_message_text("📈 Считаю...")

    output_path = f"temp_trend_{update.effective_user.id}.png"

    if trend_type == "age":
        df = data_processor.get_age_trend(stat, min_nineties=5.0)
        if df.empty:
            await query.edit_message_text(
                "Недостаточно данных для этой статистики.",
                reply_markup=again_keyboard(),
            )
            return MAIN_MENU
        visualizer.create_age_trend_chart(
            df, stat_label, "Все позиции · Все лиги", output_path
        )
        caption = f"📈 «{stat_label}» по возрасту"
    else:
        df = data_processor.get_league_trend(stat, min_nineties=5.0)
        if df.empty:
            await query.edit_message_text(
                "Недостаточно данных для этой статистики.",
                reply_markup=again_keyboard(),
            )
            return MAIN_MENU
        visualizer.create_league_trend_chart(df, stat_label, "Все позиции", output_path)
        caption = f"🏆 «{stat_label}» по лигам"

    with open(output_path, "rb") as photo:
        await context.bot.send_photo(
            chat_id=update.effective_chat.id, photo=photo, caption=caption
        )
    if os.path.exists(output_path):
        os.remove(output_path)

    await context.bot.send_message(
        chat_id=update.effective_chat.id,
        text="Хотите ещё что-нибудь посмотреть?",
        reply_markup=again_keyboard(),
    )
    return MAIN_MENU


# ---------------------------------------------------------------------- #
# Bootstrapping
# ---------------------------------------------------------------------- #
def build_application(token: str) -> Application:
    application = Application.builder().token(token).build()

    conv_handler = ConversationHandler(
        entry_points=[CommandHandler("start", start)],
        states={
            MAIN_MENU: [
                CallbackQueryHandler(on_main_menu, pattern="^menu:"),
                CallbackQueryHandler(on_continue, pattern="^cont:"),
            ],
            CHOOSE_COMPETITION: [
                CallbackQueryHandler(on_competition, pattern="^comp:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            CHOOSE_POSITION: [
                CallbackQueryHandler(on_position, pattern="^pos:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            CHOOSE_STAT: [
                CallbackQueryHandler(on_stat_page, pattern="^statpage:"),
                CallbackQueryHandler(on_stat, pattern="^stat:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
                CallbackQueryHandler(noop, pattern="^noop$"),
            ],
            CMP_SEARCH_1: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, on_search_player1)
            ],
            CMP_PICK_1: [
                CallbackQueryHandler(on_pick_player1, pattern="^p1:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            CMP_SEARCH_2: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, on_search_player2)
            ],
            CMP_PICK_2: [
                CallbackQueryHandler(on_pick_player2, pattern="^p2:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            SCATTER_COMPETITION: [
                CallbackQueryHandler(on_scatter_competition, pattern="^comp:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            SCATTER_POSITION: [
                CallbackQueryHandler(on_scatter_position, pattern="^pos:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            SCATTER_METRIC: [
                CallbackQueryHandler(on_scatter_metric, pattern="^smetric:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            SIMILAR_SEARCH: [
                MessageHandler(filters.TEXT & ~filters.COMMAND, on_search_similar)
            ],
            SIMILAR_PICK: [
                CallbackQueryHandler(on_pick_similar, pattern="^sim:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            TREND_TYPE: [
                CallbackQueryHandler(on_trend_type, pattern="^trendtype:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
            ],
            TREND_STAT: [
                CallbackQueryHandler(on_trend_stat_page, pattern="^statpage:"),
                CallbackQueryHandler(on_trend_stat, pattern="^stat:"),
                CallbackQueryHandler(on_back, pattern="^back:"),
                CallbackQueryHandler(noop, pattern="^noop$"),
            ],
        },
        fallbacks=[CommandHandler("cancel", cancel), CommandHandler("start", start)],
    )

    application.add_handler(conv_handler)
    application.add_handler(CommandHandler("help", help_command))
    return application


def main():
    """Regular entrypoint for `python telegram_bot.py` (plain script, no
    already-running event loop). Do NOT use this from a Colab/Jupyter cell —
    use run_in_notebook() instead, see below."""
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        print("ERROR: set TELEGRAM_BOT_TOKEN environment variable.")
        return
    if data_processor is None:
        print(f"ERROR: data processor not initialized. Check FOOTBALL_CSV_PATH={CSV_PATH}")
        return

    application = build_application(token)
    print("Bot is starting...")
    application.run_polling(allowed_updates=Update.ALL_TYPES, stop_signals=None)


async def run_in_notebook(token: Optional[str] = None):
    """Colab/Jupyter-friendly entrypoint.

    `Application.run_polling()` is a blocking helper that tries to manage
    (and close) its own event loop — that clashes with the loop the notebook
    kernel already runs, producing "Cannot close a running event loop" when
    the cell is stopped. Calling the async pieces directly and awaiting them
    from a notebook cell (top-level `await` works in Colab/Jupyter) sidesteps
    that entirely.

    Usage in a Colab cell:
        from telegram_bot import run_in_notebook
        await run_in_notebook()          # reads TELEGRAM_BOT_TOKEN from env
        # or: await run_in_notebook("123456:ABC-your-token")

    Stop it with the cell's "Interrupt execution" (■) button — that raises
    KeyboardInterrupt, which is caught below and shuts the bot down cleanly.
    """
    token = token or os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        print("ERROR: set TELEGRAM_BOT_TOKEN environment variable or pass token=...")
        return
    if data_processor is None:
        print(f"ERROR: data processor not initialized. Check FOOTBALL_CSV_PATH={CSV_PATH}")
        return

    application = build_application(token)
    print("Bot is starting (notebook mode)... interrupt the cell to stop it.")

    await application.initialize()
    await application.start()
    await application.updater.start_polling(allowed_updates=Update.ALL_TYPES)
    try:
        await asyncio.Event().wait()  # keep the coroutine alive until interrupted
    except (KeyboardInterrupt, asyncio.CancelledError):
        pass
    finally:
        print("Stopping bot...")
        await application.updater.stop()
        await application.stop()
        await application.shutdown()
        print("Bot stopped.")


if __name__ == "__main__":
    main()